### ISSUE TITLE
max comparisons break if sense includes diff comparisons

### ISSUE THREAD

**Issue by kartiksubbarao** [tommyod/paretoset#18]
If the `sense` parameter to `paretoset()` includes a **diff** comparsion, all other **max** comparisons return the opposite of the correct value. Example:
```
In [10]: paretoset([[2,0], [1,0], [0,1]], ['max', 'diff'])
Out[10]: array([False,  True,  True])
```
This cause appears to be in this section:

https://github.com/tommyod/paretoset/blob/0c01636c0e10c16dad080dde2d741586a4fc55aa/paretoset/user_interface.py#L94-L101

The loop to invert the sign of the `max_cols` columns is only executed if there are no `diff_cols`. If diff columns are present, this loop is skipped.

**Comment by tommyod** [comment]
Thanks for the detailed report @kartiksubbarao . Would you like to create a PR? If not, I'll fix it when I have the time :+1:

**Comment by kartiksubbarao** [comment]
Sure, here you go, feel free to tweak as desired. I ran through test_api.py and test_algorithms.py and there were no errors. The patch also updates one of the diff tests in test_api.py to check for this scenario.
