### ISSUE TITLE
How should I cite your work?

### ISSUE THREAD

**Issue by wagerc97** [tommyod/paretoset#37]
Hi, I use your library in my thesis. How should I cite your software? 
Really good work, I love how easy it is to use!

Best, 
Clemens

**Comment by tommyod** [comment]
Thanks!

I appreciate citations! I don't have any paper or DOI for this project. If you include a link to GitHub I am happy. Maybe just "paretoset v1.2.3, https://github.com/tommyod/paretoset", or something like that. Depending a bit on how formal you want to be :)

**Comment by wagerc97** [comment]
Alright, I will include the link and give detailed information :)

Cheers!
