### ISSUE TITLE
SystemError: initialization of _internal failed without raising an exception

### ISSUE THREAD

**Issue by ZAINEBCHELLY** [tommyod/paretoset#38]
---------------------------------------------------------------------------
SystemError                               Traceback (most recent call last)
Cell In[1], line 1
----> 1 from paretoset import paretoset
      2 import pandas as pd
      4 hotels = pd.DataFrame({"price": [50, 53, 62, 87, 83, 39, 60, 44], 
      5                        "distance_to_beach": [13, 21, 19, 13, 5, 22, 22, 25]})

File ~\anaconda3\lib\site-packages\paretoset\__init__.py:13
     10 __author__ = "tommyod"
     12 import sys
---> 13 from paretoset.user_interface import paretoset, paretorank
     14 from paretoset.algorithms_numpy import crowding_distance
     17 def run_tests():

File ~\anaconda3\lib\site-packages\paretoset\user_interface.py:9
      4 from paretoset.utils import user_has_package, validate_inputs
      7 import pandas as pd
----> 9 if user_has_package("numba"):
     10     from paretoset.algorithms_numba import BNL
     13 def paretoset(costs, sense=None, distinct=True, use_numba=True):

File ~\anaconda3\lib\site-packages\paretoset\utils.py:9, in user_has_package(package_name)
      7 """Check if the user has `numba` installed."""
      8 try:
----> 9     importlib.import_module(package_name, package=None)
     10     return True
     11 except ModuleNotFoundError:

File ~\anaconda3\lib\importlib\__init__.py:127, in import_module(name, package)
    125             break
    126         level += 1
--> 127 return _bootstrap._gcd_import(name[level:], package, level)

File ~\anaconda3\lib\site-packages\numba\__init__.py:42
     38 from numba.core.decorators import (cfunc, generated_jit, jit, njit, stencil,
     39                                    jit_module)
     41 # Re-export vectorize decorators and the thread layer querying function
---> 42 from numba.np.ufunc import (vectorize, guvectorize, threading_layer,
     43                             get_num_threads, set_num_threads,
     44                             set_parallel_chunksize, get_parallel_chunksize,
     45                             get_thread_id)
     47 # Re-export Numpy helpers
     48 from numba.np.numpy_support import carray, farray, from_dtype

File ~\anaconda3\lib\site-packages\numba\np\ufunc\__init__.py:3
      1 # -*- coding: utf-8 -*-
----> 3 from numba.np.ufunc.decorators import Vectorize, GUVectorize, vectorize, guvectorize
      4 from numba.np.ufunc._internal import PyUFunc_None, PyUFunc_Zero, PyUFunc_One
      5 from numba.np.ufunc import _internal, array_exprs

File ~\anaconda3\lib\site-packages\numba\np\ufunc\decorators.py:3
      1 import inspect
----> 3 from numba.np.ufunc import _internal
      4 from numba.np.ufunc.parallel import ParallelUFuncBuilder, ParallelGUFuncBuilder
      6 from numba.core.registry import DelayedRegistry

SystemError: initialization of _internal failed without raising an exception

**Comment by tommyod** [comment]
Looks like an error related to numba, not paretoset.

- Can you import numba without getting an error?
- What are the versions?

**Comment by ZAINEBCHELLY** [comment]
Thanks! I have solved irt. 
But I encountered another problem:
Now, I can run the code but I do not have any visualizations (no displayed results)
For instance, for the first cell, I had to add print(mask) and print(paretoset_hotels) to see the results:
***********************************
from paretoset import paretoset
import pandas as pd

hotels = pd.DataFrame({"price": [50, 53, 62, 87, 83, 39, 60, 44], 
                       "distance_to_beach": [13, 21, 19, 13, 5, 22, 22, 25]})
mask = paretoset(hotels, sense=["min", "min"])
print(mask)
paretoset_hotels = hotels[mask]
print(paretoset_hotels)
*********************
Results:
[ True False False False  True  True False False]
   price  distance_to_beach
0     50                 13
4     83                  5
5     39                 22

How can I print the graphs?
Thank you.

**Comment by tommyod** [comment]
You need to use a plotting library such as "matplotlib". I don't have time or capacity to help you with this. I will close this issue that it's not a problem related to this package. Check out e.g. reddit or stackoverflow or discord to get help with Python and data analysis in general. Best of luck!
